SELECT
   D.DOCTOR_ID,
   D.FRONT_TITLE,
   D.NAME,
   D.END_TITLE,
   D.CITY_ID,
   DS.SPECIALTY_ID,
   SP.ABBR,
   SP.SPECIALTY_GROUP_ID,
   D.SEX_ID,
   D.HP,
   D.EMAIL,
   D.ADDRESS
FROM
    DOCTOR D
JOIN
    DOCTOR_SPECIALTY DS ON DS.DOCTOR_ID = D.DOCTOR_ID 
JOIN
    SPECIALTY SP ON SP.SPECIALTY_ID = DS.SPECIALTY_ID 
JOIN
    SPECIALTY_GROUP SG ON SG.SPECIALTY_GROUP_ID = SP.SPECIALTY_GROUP_ID;